# google_keep\services.yaml

add_to_list:
  description: Add items to a Google Keep list.
  fields:
    list_name:
      description: Title of the Google Keep list to create or update
      example: 'Grocery'
    items:
      description: Item(s) to add to the list
      example: 'spinach and mushrooms'
